"""
Export Utilities for Transcription Results
Supports SRT, WebVTT, and Markdown formats with timestamps.
"""
from datetime import timedelta
from pathlib import Path
from typing import Dict, List, Union


def format_timestamp_srt(seconds: float) -> str:
    """
    Format seconds to SRT timestamp format: HH:MM:SS,mmm

    Args:
        seconds: Time in seconds

    Returns:
        Formatted timestamp string
    """
    td = timedelta(seconds=seconds)
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    millis = int((seconds - int(seconds)) * 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d},{millis:03d}"


def format_timestamp_vtt(seconds: float) -> str:
    """
    Format seconds to WebVTT timestamp format: HH:MM:SS.mmm

    Args:
        seconds: Time in seconds

    Returns:
        Formatted timestamp string
    """
    td = timedelta(seconds=seconds)
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    millis = int((seconds - int(seconds)) * 1000)
    return f"{hours:02d}:{minutes:02d}:{secs:02d}.{millis:03d}"


def format_timestamp_md(seconds: float) -> str:
    """
    Format seconds to Markdown timestamp format: [HH:MM:SS]

    Args:
        seconds: Time in seconds

    Returns:
        Formatted timestamp string
    """
    td = timedelta(seconds=seconds)
    total_seconds = int(td.total_seconds())
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    return f"[{hours:02d}:{minutes:02d}:{secs:02d}]"


def generate_srt(segments: List[Dict]) -> str:
    """
    Generate SRT subtitle format from transcription segments.

    Args:
        segments: List of segment dictionaries with 'start', 'end', and 'text' keys

    Returns:
        SRT formatted string
    """
    lines = []

    for i, segment in enumerate(segments, start=1):
        start_time = segment.get("start", 0)
        end_time = segment.get("end", 0)
        text = segment.get("text", "").strip()

        if not text:
            continue

        lines.append(str(i))
        lines.append(f"{format_timestamp_srt(start_time)} --> {format_timestamp_srt(end_time)}")
        lines.append(text)
        lines.append("")  # Empty line between entries

    return "\n".join(lines)


def generate_vtt(segments: List[Dict]) -> str:
    """
    Generate WebVTT subtitle format from transcription segments.

    Args:
        segments: List of segment dictionaries with 'start', 'end', and 'text' keys

    Returns:
        WebVTT formatted string
    """
    lines = ["WEBVTT", ""]

    for segment in segments:
        start_time = segment.get("start", 0)
        end_time = segment.get("end", 0)
        text = segment.get("text", "").strip()

        if not text:
            continue

        lines.append(f"{format_timestamp_vtt(start_time)} --> {format_timestamp_vtt(end_time)}")
        lines.append(text)
        lines.append("")  # Empty line between entries

    return "\n".join(lines)


def generate_markdown(segments: List[Dict], include_timestamp: bool = True) -> str:
    """
    Generate Markdown format from transcription segments.

    Args:
        segments: List of segment dictionaries with 'start', 'end', and 'text' keys
        include_timestamp: Whether to include timestamps

    Returns:
        Markdown formatted string
    """
    lines = []

    # Header
    lines.append("# Transcription")
    lines.append("")

    # Segments
    for i, segment in enumerate(segments, start=1):
        start_time = segment.get("start", 0)
        text = segment.get("text", "").strip()

        if not text:
            continue

        if include_timestamp:
            timestamp = format_timestamp_md(start_time)
            lines.append(f"{timestamp} {text}")
        else:
            lines.append(text)

    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by Audio Transcriber*")

    return "\n".join(lines)


def generate_dialogue_markdown(
    diarized_transcript: Dict,
    title: str = "Transcription",
    include_metadata: bool = True,
) -> str:
    """
    Generate Markdown format from DiarizedTranscript (对话体排版).

    Format:
        **【角色名】(时间戳):** 对话内容

    Args:
        diarized_transcript: Dict with 'turns' list containing speaker, start_time, text
        title: Document title
        include_metadata: Whether to include metadata section

    Returns:
        Markdown formatted string
    """
    lines = []

    # Header
    lines.append(f"# {title}")
    lines.append("")

    # Metadata section
    if include_metadata:
        speakers = diarized_transcript.get("speakers", [])
        if speakers:
            lines.append("## 参与者")
            lines.append("")
            for speaker in speakers:
                lines.append(f"- {speaker}")
            lines.append("")

    # Dialogue section
    lines.append("## 对话内容")
    lines.append("")

    turns = diarized_transcript.get("turns", [])
    for turn in turns:
        speaker = turn.get("speaker", "未知")
        start_time = turn.get("start_time", "")
        text = turn.get("text", "").strip()
        emotion = turn.get("emotion", "")

        if not text:
            continue

        # Format: **【角色名】(时间戳)[情绪]:** 对话内容
        emotion_tag = f"[{emotion}]" if emotion else ""
        if start_time:
            lines.append(f"**【{speaker}】({start_time}){emotion_tag}:** {text}")
        else:
            lines.append(f"**【{speaker}】{emotion_tag}:** {text}")

    # Footer
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("*Generated by Audio Transcriber with Semantic Diarization*")

    return "\n".join(lines)


def save_all_formats(
    segments: List[Dict],
    base_path: str = None,
    filename_base: str = None,
    output_dir: str = None,
    base_name: str = None,
    title: str = "Transcription",
    insights: Dict = None,
    skills_applied: int = 0,
) -> Dict[str, str]:
    """
    Save transcription in all available formats.

    Args:
        segments: List of transcription segments
        base_path: Base directory path (alias for output_dir)
        filename_base: Base filename without extension (alias for base_name)
        output_dir: Output directory path
        base_name: Base filename without extension
        title: Document title
        insights: Document insights dictionary
        skills_applied: Number of skills applied

    Returns:
        Dictionary mapping format names to file paths
    """
    # Handle parameter aliases
    output_path = output_dir or base_path or "output"
    file_base = base_name or filename_base or "transcription"
    
    Path(output_path).mkdir(parents=True, exist_ok=True)

    output_files = {}

    # Plain text
    txt_content = "\n".join([s.get("text", "").strip() for s in segments if s.get("text", "").strip()])
    txt_path = Path(output_path) / f"{file_base}.txt"
    with open(txt_path, "w", encoding="utf-8") as f:
        f.write(txt_content)
    output_files["txt"] = str(txt_path)

    # SRT
    srt_path = Path(output_path) / f"{file_base}.srt"
    srt_content = generate_srt(segments)
    with open(srt_path, "w", encoding="utf-8") as f:
        f.write(srt_content)
    output_files["srt"] = str(srt_path)

    # VTT
    vtt_path = Path(output_path) / f"{file_base}.vtt"
    vtt_content = generate_vtt(segments)
    with open(vtt_path, "w", encoding="utf-8") as f:
        f.write(vtt_content)
    output_files["vtt"] = str(vtt_path)

    # Markdown with enhanced content if insights available
    md_path = Path(output_path) / f"{file_base}.md"
    if insights:
        md_content = _generate_enhanced_markdown(segments, title, insights, skills_applied)
    else:
        md_content = generate_markdown(segments)
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(md_content)
    output_files["md"] = str(md_path)

    return output_files


def _generate_enhanced_markdown(
    segments: List[Dict],
    title: str,
    insights: Dict,
    skills_applied: int,
) -> str:
    """Generate enhanced Markdown with insights."""
    lines = []
    
    # Header
    lines.append(f"# {title}")
    lines.append("")
    
    # TL;DR section
    tldr = insights.get("tldr", "")
    if tldr:
        lines.append("## TL;DR")
        lines.append("")
        lines.append(tldr)
        lines.append("")
    
    # Key points
    key_points = insights.get("key_points", [])
    if key_points:
        lines.append("## 要点")
        lines.append("")
        for point in key_points:
            lines.append(f"- {point}")
        lines.append("")
    
    # Chapters
    chapters = insights.get("chapters", [])
    if chapters:
        lines.append("## 章节")
        lines.append("")
        for chapter in chapters:
            ts = chapter.get("timestamp", "")
            ch_title = chapter.get("title", "")
            ch_summary = chapter.get("summary", "")
            lines.append(f"### [{ts}] {ch_title}")
            lines.append("")
            lines.append(ch_summary)
            lines.append("")
    
    # Transcription content
    lines.append("## 完整转录")
    lines.append("")
    for segment in segments:
        start = segment.get("start", 0)
        text = segment.get("text", "").strip()
        if text:
            timestamp = format_timestamp_md(start)
            lines.append(f"{timestamp} {text}")
    
    lines.append("")
    lines.append("---")
    lines.append("")
    lines.append(f"*Generated by Audio Transcriber | Skills applied: {skills_applied}*")
    
    return "\n".join(lines)
